name: Deploy to WP Engine
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest  
    steps: 
    - uses: actions/checkout@v2
    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v2.3.3
      with:
      
      # Deploy vars 
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}

      # Branches & Environments 
        PRD_BRANCH: main # GitHub Production Branch
        PRD_ENV: ivycat # WPEngine Production Environment
        
        STG_BRANCH: staging # GitHub Staging Branch
        STG_ENV: ivycatstg # WPEngine Staging Environment
        
        DEV_BRANCH: development # GitHub Development Branch
        DEV_ENV: ivycatdev # WPEngine Development Environment

      # Optional/On-Demand
        # PHP_LINT: TRUE
        # FLAGS: -azvr --inplace --delete --exclude=".*" --exclude-from=.deployignore
        # CACHE_CLEAR: TRUE
        # TPO_SRC_PATH: "wp-content/themes/your-theme/"
        # TPO_PATH: "wp-content/themes/your-theme/"